kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "jbpm-build" 
spec:
  runPolicy: "Serial" 
  source: 
    git:
      uri: "https://github.com/engineering-do-brasil/jbpm.git"
  strategy: 
    dockerStrategy:
      dockerfilePath: Dockerfile